import{a as D,S as E,i}from"./assets/vendor-DQvd0HNi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function g(o,r){const e="https://pixabay.com"+"/api/",t={key:"55027446-560ad86223e1945ccd495c8f6",q:o,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await D.get(e,{params:t})).data}catch(a){throw console.log(a),a}}const M=new E(".gallery a",{captionDelay:250,captionsData:"alt"}),f=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".btn-load");function y(o,r=!1){const s=o.map(n=>{const{webformatURL:e,largeImageURL:t,tags:a,likes:v,views:q,comments:S,downloads:P}=n;return`<li class="item">
        <a class="img-photo" href="${t}"><img src="${e}" alt="${a}"></a>
        <div class="wrap-info">
            <p class="info">Likes ${v}</p>
            <p class="info">Views ${q}</p>
            <p class="info">Comments ${S}</p>
            <p class="info">Downloads ${P}</p>
        </div>
      </li>`}).join("");r?f.insertAdjacentHTML("beforeend",s):f.innerHTML=s,M.refresh()}function $(){f.innerHTML=""}function L(){h.classList.remove("is-hidden")}function m(){h.classList.add("is-hidden")}function O(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}const b={formEl:document.querySelector(".form"),btnLoad:document.querySelector(".btn-load")},x=15;let l,c,d;m();u();b.formEl.addEventListener("submit",async o=>{if(o.preventDefault(),l=new FormData(o.target).get("search-text"),l.trim()==="")return i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});$(),L(),u(),c=1;try{const s=await g(l,c);y(s.hits),d=Math.ceil(s.totalHits/x),d===0&&i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}catch(s){i.error({message:s})}m(),w(),o.target.reset()});b.btnLoad.addEventListener("click",async o=>{u(),L(),c+=1;try{const r=await g(l,c);y(r.hits,!0),B()}catch(r){i.error({message:r})}w(),m()});function w(){c>=d?(u(),d>0&&i.info({message:"We're sorry, but you've reached the end of search results."})):O()}function B(){const o=document.querySelector(".item");if(!o)return;const r=o.getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
