import{a as v,S as q,i as l}from"./assets/vendor-DQvd0HNi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function m(o,r){const e="https://pixabay.com"+"/api/",t={key:"55027446-560ad86223e1945ccd495c8f6",q:o,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};return await v.get(e,{params:t}).then(a=>a.data).catch(a=>{console.log(a)})}const S=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".btn-load");function P(o){const{webformatURL:r,largeImageURL:s,tags:n,likes:e,views:t,comments:a,downloads:w}=o;return`<li class="item">
        <a class="img-photo" href="${s}"><img src="${r}" alt="${n}"></a>
        <div class="wrap-info">
            <p class="info">Likes ${e}</p>
            <p class="info">Views ${t}</p>
            <p class="info">Comments ${a}</p>
            <p class="info">Downloads ${w}</p>
        </div>
      </li>`}function y(o){return o.map(P).join("")}function h(){new q(".gallery a",{captionDelay:250,captionsData:"alt"}).refresh()}function D(){S.innerHTML=""}function x(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}function M(){p.classList.remove("hidden")}function f(){p.classList.add("hidden")}const c={formEl:document.querySelector(".form"),galleryList:document.querySelector(".gallery"),btnLoad:document.querySelector(".btn-load")},$=15;let d,i,u;L();f();c.formEl.addEventListener("submit",async o=>{o.preventDefault(),d=new FormData(o.target).get("search-text"),D(),x(),i=1;try{const s=await m(d,i),n=y(s.hits);c.galleryList.innerHTML=n,h(),u=Math.ceil(s.totalHits/$),u===0&&l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}catch(s){l.info({message:s})}L(),b(),o.target.reset()});c.btnLoad.addEventListener("click",async o=>{i+=1,f();try{const r=await m(d,i),s=y(r.hits);c.galleryList.insertAdjacentHTML("beforeend",s),E()}catch(r){l.error({message:r})}h(),b()});function b(){i>=u?f():M()}function E(){window.scrollBy({top:1e3,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
